name: Secret Access

on: [push]

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Secret in Node.js
        env:
          MY_SECRET: ${{ secrets.WEBHOOK_URL }}
        run: echo "Secret is set!"
